### ISSUE TITLE
jjardon hit an install fail in a chroot...

### ISSUE THREAD

**Issue by devcurmudgeon** [CodethinkLabs/sandboxlib#15]
[jjardon@eregion definitions]$ sudo pip2 install pyyaml sandboxlib
Requirement already satisfied (use --upgrade to upgrade): pyyaml in /usr/lib/python2.7/site-packages
Collecting sandboxlib
  Using cached sandboxlib-0.3.1.tar.gz
    Complete output from command python setup.py egg_info:
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/pbr/core.py", line 104, in pbr
        attrs = util.cfg_to_args(path)
      File "/usr/lib/python2.7/site-packages/pbr/util.py", line 256, in cfg_to_args
        wrap_commands(kwargs)
      File "/usr/lib/python2.7/site-packages/pbr/util.py", line 477, in wrap_commands
        for cmd, _ in dist.get_command_list():
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 447, in get_command_list
        cmdclass = ep.resolve()
      File "/usr/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2386, in resolve
        module = **import**(self.module_name, fromlist=['**name**'], level=0)
      File "/usr/lib/python2.7/site-packages/pbr/testr_command.py", line 47, in <module>
        from testrepository import commands
    ImportError: No module named testrepository
    error in setup command: Error parsing /tmp/pip-build-9VcwQc/sandboxlib/setup.cfg: ImportError: No module named testrepository

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-9VcwQc/sandboxlib

**Comment by richardmaw-codethink** [comment]
Looks like a bug in pbr to me.
