### ISSUE TITLE
SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC on attempting to upgrade

### ISSUE THREAD

**Issue by devcurmudgeon** [CodethinkLabs/sandboxlib#7]
/src/ybd # pip install --upgrade sandboxlib
Downloading/unpacking sandboxlib from https://pypi.python.org/packages/source/s/sandboxlib/sandboxlib-0.3.1.tar.gz#md5=8e5f0c7b9ad3f267606ea97912eb9bcb
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 295, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/site-packages/pip/req.py", line 1197, in prepare_files
    do_download,
  File "/usr/lib/python2.7/site-packages/pip/req.py", line 1375, in unpack_url
    self.session,
  File "/usr/lib/python2.7/site-packages/pip/download.py", line 546, in unpack_http_url
    resp = session.get(target_url, stream=True)
  File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 468, in get
    return self.request('GET', url, *_kwargs)
  File "/usr/lib/python2.7/site-packages/pip/download.py", line 237, in request
    return super(PipSession, self).request(method, url, *args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 456, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 559, in send
    r = adapter.send(request, *_kwargs)
  File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 382, in send
    raise SSLError(e, request=request)
SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1750)

Storing debug log for failure in /root/.pip/pip.log

**Comment by devcurmudgeon** [comment]
but then on re-running it worked. maybe network issue my end?

**Comment by ghost** [comment]
Seems like a network issue and/or a bug in https://github.com/pypa/pip, I don't know what could be done to fix this on the sandboxlib side, other than trying out other packaging methods.
